### PR TITLE
Added line in README.md to download `rustup`

### PR DESCRIPTION
**Pull request by ZeroOneLabs**
When I went to install `rustup` it complained that I can't install `rustup` along with Rust.

### CODE REVIEW

**Comment by 0xhiro** [comment]
Oh yeah! my bad! I should have linked the Rust website instead.
But this pull request modified more lines than necessary. If the link was the only change, can you revert to changing only that line?

**Comment by ZeroOneLabs** [comment]
Oops! Must've been my markdown linter. My bad! I'll change that.

**Comment by ZeroOneLabs** [comment]
fix0red  :]

**Comment by 0xhiro** [comment]
Well... it still looks the same. You can check the `Files changed` tab to ensure only the line of the link is changed

**Pull request closed without merging**
